/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */





declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CategoriesFrontendOnBackendCreateManyCategoryBackendInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    frontendId: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoriesFrontendOnBackendCreateManyCategoryBackendInputEnvelope: { // input type
    data?: NexusGenInputs['CategoriesFrontendOnBackendCreateManyCategoryBackendInput'][] | null; // [CategoriesFrontendOnBackendCreateManyCategoryBackendInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  CategoriesFrontendOnBackendCreateManyCategoryFrontendInput: { // input type
    backendId: number; // Int!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoriesFrontendOnBackendCreateManyCategoryFrontendInputEnvelope: { // input type
    data?: NexusGenInputs['CategoriesFrontendOnBackendCreateManyCategoryFrontendInput'][] | null; // [CategoriesFrontendOnBackendCreateManyCategoryFrontendInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryBackendInput: { // input type
    connect?: NexusGenInputs['CategoriesFrontendOnBackendWhereUniqueInput'][] | null; // [CategoriesFrontendOnBackendWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CategoriesFrontendOnBackendCreateOrConnectWithoutCategoryBackendInput'][] | null; // [CategoriesFrontendOnBackendCreateOrConnectWithoutCategoryBackendInput!]
    create?: NexusGenInputs['CategoriesFrontendOnBackendCreateWithoutCategoryBackendInput'][] | null; // [CategoriesFrontendOnBackendCreateWithoutCategoryBackendInput!]
    createMany?: NexusGenInputs['CategoriesFrontendOnBackendCreateManyCategoryBackendInputEnvelope'] | null; // CategoriesFrontendOnBackendCreateManyCategoryBackendInputEnvelope
  }
  CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryFrontendInput: { // input type
    connect?: NexusGenInputs['CategoriesFrontendOnBackendWhereUniqueInput'][] | null; // [CategoriesFrontendOnBackendWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CategoriesFrontendOnBackendCreateOrConnectWithoutCategoryFrontendInput'][] | null; // [CategoriesFrontendOnBackendCreateOrConnectWithoutCategoryFrontendInput!]
    create?: NexusGenInputs['CategoriesFrontendOnBackendCreateWithoutCategoryFrontendInput'][] | null; // [CategoriesFrontendOnBackendCreateWithoutCategoryFrontendInput!]
    createMany?: NexusGenInputs['CategoriesFrontendOnBackendCreateManyCategoryFrontendInputEnvelope'] | null; // CategoriesFrontendOnBackendCreateManyCategoryFrontendInputEnvelope
  }
  CategoriesFrontendOnBackendCreateOrConnectWithoutCategoryBackendInput: { // input type
    create: NexusGenInputs['CategoriesFrontendOnBackendCreateWithoutCategoryBackendInput']; // CategoriesFrontendOnBackendCreateWithoutCategoryBackendInput!
    where: NexusGenInputs['CategoriesFrontendOnBackendWhereUniqueInput']; // CategoriesFrontendOnBackendWhereUniqueInput!
  }
  CategoriesFrontendOnBackendCreateOrConnectWithoutCategoryFrontendInput: { // input type
    create: NexusGenInputs['CategoriesFrontendOnBackendCreateWithoutCategoryFrontendInput']; // CategoriesFrontendOnBackendCreateWithoutCategoryFrontendInput!
    where: NexusGenInputs['CategoriesFrontendOnBackendWhereUniqueInput']; // CategoriesFrontendOnBackendWhereUniqueInput!
  }
  CategoriesFrontendOnBackendCreateWithoutCategoryBackendInput: { // input type
    categoryFrontend: NexusGenInputs['CategoryFrontendCreateNestedOneWithoutCategoriesInput']; // CategoryFrontendCreateNestedOneWithoutCategoriesInput!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoriesFrontendOnBackendCreateWithoutCategoryFrontendInput: { // input type
    categoryBackend: NexusGenInputs['CategoryBackendCreateNestedOneWithoutCategoriesInput']; // CategoryBackendCreateNestedOneWithoutCategoriesInput!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoriesFrontendOnBackendFrontendIdBackendIdCompoundUniqueInput: { // input type
    backendId: number; // Int!
    frontendId: number; // Int!
  }
  CategoriesFrontendOnBackendWhereUniqueInput: { // input type
    frontendId_backendId?: NexusGenInputs['CategoriesFrontendOnBackendFrontendIdBackendIdCompoundUniqueInput'] | null; // CategoriesFrontendOnBackendFrontendIdBackendIdCompoundUniqueInput
  }
  CategoryBackendCreateInput: { // input type
    categories?: NexusGenInputs['CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryBackendInput'] | null; // CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryBackendInput
    children?: NexusGenInputs['CategoryBackendCreateNestedManyWithoutParentInput'] | null; // CategoryBackendCreateNestedManyWithoutParentInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    level?: number | null; // Int
    name: string; // String!
    parent?: NexusGenInputs['CategoryBackendCreateNestedOneWithoutChildrenInput'] | null; // CategoryBackendCreateNestedOneWithoutChildrenInput
    show?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryBackendCreateManyParentInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    level?: number | null; // Int
    name: string; // String!
    show?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryBackendCreateManyParentInputEnvelope: { // input type
    data?: NexusGenInputs['CategoryBackendCreateManyParentInput'][] | null; // [CategoryBackendCreateManyParentInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  CategoryBackendCreateNestedManyWithoutParentInput: { // input type
    connect?: NexusGenInputs['CategoryBackendWhereUniqueInput'][] | null; // [CategoryBackendWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CategoryBackendCreateOrConnectWithoutParentInput'][] | null; // [CategoryBackendCreateOrConnectWithoutParentInput!]
    create?: NexusGenInputs['CategoryBackendCreateWithoutParentInput'][] | null; // [CategoryBackendCreateWithoutParentInput!]
    createMany?: NexusGenInputs['CategoryBackendCreateManyParentInputEnvelope'] | null; // CategoryBackendCreateManyParentInputEnvelope
  }
  CategoryBackendCreateNestedOneWithoutCategoriesInput: { // input type
    connect?: NexusGenInputs['CategoryBackendWhereUniqueInput'] | null; // CategoryBackendWhereUniqueInput
    connectOrCreate?: NexusGenInputs['CategoryBackendCreateOrConnectWithoutCategoriesInput'] | null; // CategoryBackendCreateOrConnectWithoutCategoriesInput
    create?: NexusGenInputs['CategoryBackendCreateWithoutCategoriesInput'] | null; // CategoryBackendCreateWithoutCategoriesInput
  }
  CategoryBackendCreateNestedOneWithoutChildrenInput: { // input type
    connect?: NexusGenInputs['CategoryBackendWhereUniqueInput'] | null; // CategoryBackendWhereUniqueInput
    connectOrCreate?: NexusGenInputs['CategoryBackendCreateOrConnectWithoutChildrenInput'] | null; // CategoryBackendCreateOrConnectWithoutChildrenInput
    create?: NexusGenInputs['CategoryBackendCreateWithoutChildrenInput'] | null; // CategoryBackendCreateWithoutChildrenInput
  }
  CategoryBackendCreateOrConnectWithoutCategoriesInput: { // input type
    create: NexusGenInputs['CategoryBackendCreateWithoutCategoriesInput']; // CategoryBackendCreateWithoutCategoriesInput!
    where: NexusGenInputs['CategoryBackendWhereUniqueInput']; // CategoryBackendWhereUniqueInput!
  }
  CategoryBackendCreateOrConnectWithoutChildrenInput: { // input type
    create: NexusGenInputs['CategoryBackendCreateWithoutChildrenInput']; // CategoryBackendCreateWithoutChildrenInput!
    where: NexusGenInputs['CategoryBackendWhereUniqueInput']; // CategoryBackendWhereUniqueInput!
  }
  CategoryBackendCreateOrConnectWithoutParentInput: { // input type
    create: NexusGenInputs['CategoryBackendCreateWithoutParentInput']; // CategoryBackendCreateWithoutParentInput!
    where: NexusGenInputs['CategoryBackendWhereUniqueInput']; // CategoryBackendWhereUniqueInput!
  }
  CategoryBackendCreateWithoutCategoriesInput: { // input type
    children?: NexusGenInputs['CategoryBackendCreateNestedManyWithoutParentInput'] | null; // CategoryBackendCreateNestedManyWithoutParentInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    level?: number | null; // Int
    name: string; // String!
    parent?: NexusGenInputs['CategoryBackendCreateNestedOneWithoutChildrenInput'] | null; // CategoryBackendCreateNestedOneWithoutChildrenInput
    show?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryBackendCreateWithoutChildrenInput: { // input type
    categories?: NexusGenInputs['CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryBackendInput'] | null; // CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryBackendInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    level?: number | null; // Int
    name: string; // String!
    parent?: NexusGenInputs['CategoryBackendCreateNestedOneWithoutChildrenInput'] | null; // CategoryBackendCreateNestedOneWithoutChildrenInput
    show?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryBackendCreateWithoutParentInput: { // input type
    categories?: NexusGenInputs['CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryBackendInput'] | null; // CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryBackendInput
    children?: NexusGenInputs['CategoryBackendCreateNestedManyWithoutParentInput'] | null; // CategoryBackendCreateNestedManyWithoutParentInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    level?: number | null; // Int
    name: string; // String!
    show?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryBackendWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  CategoryFrontendCreateManyParentInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    icon?: string | null; // String
    id?: number | null; // Int
    image?: string | null; // String
    name: string; // String!
    show?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryFrontendCreateManyParentInputEnvelope: { // input type
    data?: NexusGenInputs['CategoryFrontendCreateManyParentInput'][] | null; // [CategoryFrontendCreateManyParentInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  CategoryFrontendCreateNestedManyWithoutParentInput: { // input type
    connect?: NexusGenInputs['CategoryFrontendWhereUniqueInput'][] | null; // [CategoryFrontendWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CategoryFrontendCreateOrConnectWithoutParentInput'][] | null; // [CategoryFrontendCreateOrConnectWithoutParentInput!]
    create?: NexusGenInputs['CategoryFrontendCreateWithoutParentInput'][] | null; // [CategoryFrontendCreateWithoutParentInput!]
    createMany?: NexusGenInputs['CategoryFrontendCreateManyParentInputEnvelope'] | null; // CategoryFrontendCreateManyParentInputEnvelope
  }
  CategoryFrontendCreateNestedOneWithoutCategoriesInput: { // input type
    connect?: NexusGenInputs['CategoryFrontendWhereUniqueInput'] | null; // CategoryFrontendWhereUniqueInput
    connectOrCreate?: NexusGenInputs['CategoryFrontendCreateOrConnectWithoutCategoriesInput'] | null; // CategoryFrontendCreateOrConnectWithoutCategoriesInput
    create?: NexusGenInputs['CategoryFrontendCreateWithoutCategoriesInput'] | null; // CategoryFrontendCreateWithoutCategoriesInput
  }
  CategoryFrontendCreateNestedOneWithoutChildrenInput: { // input type
    connect?: NexusGenInputs['CategoryFrontendWhereUniqueInput'] | null; // CategoryFrontendWhereUniqueInput
    connectOrCreate?: NexusGenInputs['CategoryFrontendCreateOrConnectWithoutChildrenInput'] | null; // CategoryFrontendCreateOrConnectWithoutChildrenInput
    create?: NexusGenInputs['CategoryFrontendCreateWithoutChildrenInput'] | null; // CategoryFrontendCreateWithoutChildrenInput
  }
  CategoryFrontendCreateOrConnectWithoutCategoriesInput: { // input type
    create: NexusGenInputs['CategoryFrontendCreateWithoutCategoriesInput']; // CategoryFrontendCreateWithoutCategoriesInput!
    where: NexusGenInputs['CategoryFrontendWhereUniqueInput']; // CategoryFrontendWhereUniqueInput!
  }
  CategoryFrontendCreateOrConnectWithoutChildrenInput: { // input type
    create: NexusGenInputs['CategoryFrontendCreateWithoutChildrenInput']; // CategoryFrontendCreateWithoutChildrenInput!
    where: NexusGenInputs['CategoryFrontendWhereUniqueInput']; // CategoryFrontendWhereUniqueInput!
  }
  CategoryFrontendCreateOrConnectWithoutParentInput: { // input type
    create: NexusGenInputs['CategoryFrontendCreateWithoutParentInput']; // CategoryFrontendCreateWithoutParentInput!
    where: NexusGenInputs['CategoryFrontendWhereUniqueInput']; // CategoryFrontendWhereUniqueInput!
  }
  CategoryFrontendCreateWithoutCategoriesInput: { // input type
    children?: NexusGenInputs['CategoryFrontendCreateNestedManyWithoutParentInput'] | null; // CategoryFrontendCreateNestedManyWithoutParentInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    icon?: string | null; // String
    image?: string | null; // String
    name: string; // String!
    parent?: NexusGenInputs['CategoryFrontendCreateNestedOneWithoutChildrenInput'] | null; // CategoryFrontendCreateNestedOneWithoutChildrenInput
    show?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryFrontendCreateWithoutChildrenInput: { // input type
    categories?: NexusGenInputs['CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryFrontendInput'] | null; // CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryFrontendInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    icon?: string | null; // String
    image?: string | null; // String
    name: string; // String!
    parent?: NexusGenInputs['CategoryFrontendCreateNestedOneWithoutChildrenInput'] | null; // CategoryFrontendCreateNestedOneWithoutChildrenInput
    show?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryFrontendCreateWithoutParentInput: { // input type
    categories?: NexusGenInputs['CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryFrontendInput'] | null; // CategoriesFrontendOnBackendCreateNestedManyWithoutCategoryFrontendInput
    children?: NexusGenInputs['CategoryFrontendCreateNestedManyWithoutParentInput'] | null; // CategoryFrontendCreateNestedManyWithoutParentInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    icon?: string | null; // String
    image?: string | null; // String
    name: string; // String!
    show?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryFrontendWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  CategoryBackend: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    level: number; // Int!
    name: string; // String!
    parentId?: number | null; // Int
    show: boolean; // Boolean!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  CategoryBackend: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    level: number; // Int!
    name: string; // String!
    parentId: number | null; // Int
    show: boolean; // Boolean!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: { // field return type
    createOneCategoryBackend: NexusGenRootTypes['CategoryBackend']; // CategoryBackend!
  }
  Query: { // field return type
    categoriesBackend: Array<NexusGenRootTypes['CategoryBackend'] | null>; // [CategoryBackend]!
  }
}

export interface NexusGenFieldTypeNames {
  CategoryBackend: { // field return type name
    createdAt: 'DateTime'
    id: 'Int'
    level: 'Int'
    name: 'String'
    parentId: 'Int'
    show: 'Boolean'
    updatedAt: 'DateTime'
  }
  Mutation: { // field return type name
    createOneCategoryBackend: 'CategoryBackend'
  }
  Query: { // field return type name
    categoriesBackend: 'CategoryBackend'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneCategoryBackend: { // args
      data: NexusGenInputs['CategoryBackendCreateInput']; // CategoryBackendCreateInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}